<?php

use Illuminate\Database\Seeder;

class LocalitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('localities')->insert([
            ['nombre' => 'Angres',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Alcoy',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Alicante',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Benidorm',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Benisa',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Calpe',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Callosa de Segura',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Alcoy',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Denia',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Alcoy',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Crevillente',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Torrevieja',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Villena',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Sant Pola',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Pego',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Ibi',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Javea',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Elche',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Denia',
             'idProvincia' => 1,
            ],
            ['nombre' => 'Albacete',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Alcaraz',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Alcala del Jucar',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Carcelen',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Nerpio',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Peñosca',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Villamalea',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Almansa',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Petrola',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Socovos',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Madrigueras',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Cilanco',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Ferez',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Fuensanta',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Alcoy',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Munera',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Motilleja',
             'idProvincia' => 2,
            ],
            ['nombre' => 'Dalias',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Fondon',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Mojacar',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Chercos',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Albix',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Macael',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Huechar',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Almeria',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Beninar',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Chercos',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Matagorda',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Vicar',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Albox',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Laroya',
             'idProvincia' => 3,
            ],
            ['nombre' => 'Navia',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Corvera',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Noreña',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Tineo',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Covera',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Castropol',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Morcin',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Navia',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Castro',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Corvera',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Asturias',
             'idProvincia' => 4,
            ],
            ['nombre' => 'Arevalo',
             'idProvincia' => 5,
            ],
            ['nombre' => 'La Adrada',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Navarrevisca',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Piedrahita',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Bohoyo',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Cisla',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Balbara',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Blancha',
             'idProvincia' => 5,
            ],
            ['nombre' => 'El Tiemblo',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Avila',
             'idProvincia' => 5,
            ],
            ['nombre' => 'Barcelona',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Argentona',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Berga',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Castellar del Valles',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Cornellá del Llobregat',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Hospitaler del Llobregat',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Manlleu',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Mollet',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Molins',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Sitges',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Gava',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Parets',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Vich',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Reus',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Parents',
             'idProvincia' => 6,
            ],
            ['nombre' => 'Burgos',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Burgos',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Bricia',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Caroz',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Neila',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Mena',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Medina',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Tobalina',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Urbel',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Valdeperros',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Lerma',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Carazo',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Brivies',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Lerma',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Huerta del Rey',
             'idProvincia' => 7,
            ],
            ['nombre' => 'Roa',
             'idProvincia' => 7,
            ],

            ['nombre' => 'Caceres',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Abadia',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Acebo',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Alia',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Barrado',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Jaraicejo',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Jadrillo',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Romangordo',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Pescueza',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Belvis',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Mijadas',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Moraleja',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Villamiel',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Valdecañas',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Coria',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Cilleros',
             'idProvincia' => 8,
            ],
            ['nombre' => 'Cadiz',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Akgar',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Barbete',
             'idProvincia' => 9,
            ],
            ['nombre' => 'El GAstor',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Medina Didonia',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Paterna de Rivera',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Los Barrios',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Ubrique',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Rota',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Espera',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Algeciras',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Algar',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Chipiona',
             'idProvincia' => 9,
            ],
            ['nombre' => 'Castellon',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Alcala',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Argelita',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Herbes',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Jérica',
             'idProvincia' => 10,
            ],
            ['nombre' => 'La Llosa',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Sot',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Soneja',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Segorbe',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Sot de Ferer',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Torrechiva',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Bechi',
             'idProvincia' => 10,
            ],
            ['nombre' => 'Gerona',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Amer',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Juya',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Gorguja',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Rabos',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Rupia',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Ruimors',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Amer',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Alp',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Calabuig',
             'idProvincia' => 11,
            ],
            ['nombre' => 'Granada',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Baza',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Afarte',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Galera',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Piñar',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Nivar',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Dilar',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Hueneja',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Lucar',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Marchal',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Trevelez',
             'idProvincia' => 12,
            ],
            ['nombre' => 'Huelva',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Cartaya',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Lepe',
             'idProvincia' => 13,
            ],
            ['nombre' => 'San Silvestre',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Puerto Moral',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Galaroza',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Aroche',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Beas',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Alosno',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Alajar',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Fuenteheridos',
             'idProvincia' => 13,
            ],
            ['nombre' => 'Jaen',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Huelma',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Jamilea',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Jodar',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Linares',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Quesada',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Begijar',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Cambil',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Mancha Real',
             'idProvincia' => 14,
            ],
            ['nombre' => 'Lugo',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Baralla',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Cervantes',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Sober',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Abadin',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Burrela',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Pol',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Sarria',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Gutin',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Alfoz',
             'idProvincia' => 15,
            ],
            ['nombre' => 'Leon',
             'idProvincia' => 16,
            ],
            ['nombre' => 'Algadefe',
             'idProvincia' => 16,
            ],
            ['nombre' => 'Almanza',
             'idProvincia' => 16,
            ],
            ['nombre' => 'Ardon',
             'idProvincia' => 16,
            ],
            ['nombre' => 'Fabero',
             'idProvincia' => 16,
            ],
            ['nombre' => 'Sabero',
             'idProvincia' => 16,
            ],
            ['nombre' => 'Izagre',
             'idProvincia' => 16,
            ],
            ['nombre' => 'Borrences',
             'idProvincia' => 16,
            ],
            ['nombre' => 'La Coruña',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Ames',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Ames',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Capela',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Lousame',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Moeche',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Somozas',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Toques',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Padron',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Outes',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Satiso',
             'idProvincia' => 17,
            ],
            ['nombre' => 'Madrid',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Alcala de Henares',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Alcorcon',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Batres',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Loeches',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Puentes Viejas',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Leganes',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Alpedrete',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Berruco',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Santrocaz',
             'idProvincia' => 18,
            ],
            ['nombre' => 'El Escorial',
             'idProvincia' => 18,
            ],
            ['nombre' => 'Malaga',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Alcuacin',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Benaojo',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Ronda',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Ojen',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Casares',
             'idProvincia' => 19,
            ],
            ['nombre' => 'El Borge',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Gaucin',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Teba',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Tolox',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Torrox',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Olias',
             'idProvincia' => 19,
            ],
            ['nombre' => 'Navarra',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Garralda',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Peralta',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Ciriza',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Gesa',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Pitillas',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Atez',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Ace',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Araiz',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Allin',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Odieta',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Olaibar',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Cortes',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Garralda',
             'idProvincia' => 20,
            ],
            ['nombre' => 'Palencia',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Alar de Rey',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Loma de Ucieza',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Triollo',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Torquemada',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Saldaña',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Mantinos',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Permia',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Fromisa',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Palenzuela',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Paredes de Nava',
             'idProvincia' => 21,
            ],
            ['nombre' => 'Pontevedra',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Golada',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Gondomar',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Lalin',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Forcarey',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Oya',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Valga',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Vilaboa',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Silleada',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Rodeiro',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Poyo',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Portas',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Bueu',
             'idProvincia' => 22,
            ],
            ['nombre' => 'Soria',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Adrdadas',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Peñas',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Alrmanza',
             'idProvincia' => 23,
            ],
            ['nombre' => 'FuentePilla',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Garray',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Golmayo',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Gomara',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Reznos',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Retortillo',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Quiñoneria',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Gormaz',
             'idProvincia' => 23,
            ],
            ['nombre' => 'Sevilla',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Alanis',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Camas',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Carmona',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Estepa',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Guillena',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Paradas',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Santiponce',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Tocina',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Tomares',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Utrera',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Umbrete',
             'idProvincia' => 24,
            ],
            ['nombre' => 'Teruel',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Alcañiz',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Aba',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Alacon',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Ejulve',
             'idProvincia' => 25,
            ],
            ['nombre' => 'El Pobo',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Olba',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Orrios',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Rafaeles',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Rillo',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Riodeva',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Sarrion',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Tormon',
             'idProvincia' => 25,
            ],
            ['nombre' => 'Toledo',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Camuñas',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Mazarambroz',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Talavera de la Reina',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Villacañas',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Parillas',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Polan',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Pulsar',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Quero',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Huevas',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Gerindote',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Arges',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Almorox',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Fuensalida',
             'idProvincia' => 26,
            ],
            ['nombre' => 'Valencia',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Ademuz',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Lliria',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Meliana',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Paiporta',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Torrent',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Picanya',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Xativa',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Paterna',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Manises',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Sedavi',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Rocafort',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Fuente del hierro',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Daimuz',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Alfafar',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Aldaya',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Ayora',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Barig',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Cullera',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Mislata',
             'idProvincia' => 27,
            ],
            ['nombre' => 'Zaragoza',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Alpartir',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Aniñon',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Zaragoza',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Fayon',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Mores',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Moros',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Murero',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Moneva',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Mara',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Alborge',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Badules',
             'idProvincia' => 28,
            ],
            ['nombre' => 'Barboles',
             'idProvincia' => 28,
            ],

        ]);
    }
}
